encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki", views.index, name="wiki"),
    path("<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("add/", views.add, name="add"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("save/", views.save, name="save"),
    path("random/", views.random, name="random"),
    path("wiki/<str:title>", views.titlepage, name="titlepage"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("encyclopedia.urls")),    
    #path('add/', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import re
from django.shortcuts import render, redirect
from . import util
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from random import randint

# form for creating a new page entry
class NewPageForm(forms.Form):
    title = forms.CharField(label = "New Title")
    body = forms.CharField(label = "New Body")

# main page to show all entries
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# get the page and display it
def entry(request, title):
    html = util.convert(title)
    return render(request, "encyclopedia/entry.html", {
        "title": title, "body": html
    })

# find a page
def search(request):
    title = request.GET['q']
    if util.convert(title):       
        html = util.convert(title)
        return render(request, "encyclopedia/entry.html", {
            "title": title, "body": html
        })
  
    if util.convert(title) == False:
        entries = util.list_entries()
        matches = []
        matchCount = 0
        search = title

        for entry in entries:          
            if re.search(search, entry, re.IGNORECASE):
                matches.append(entry)
                matchCount = matchCount + 1

        if matchCount == 0:
            #matchCount = 7
            return render(request, "encyclopedia/error.html", {
            "title": title, "message": "Page Not Found."
            })            
        else: 
            return render(request, "encyclopedia/partial.html", {
                "title": title, "matches": matches
                })

#add a new page
def add(request):
    return render(request, "encyclopedia/add.html", {
        "form": NewPageForm()
    })

# save an entry
def save(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)

        if form.is_valid():            
            title = form.cleaned_data["title"]
            entries = util.list_entries()
            for entry in entries:
                if entry == form.cleaned_data["title"]:
                    return render(request, "encyclopedia/error.html", {
                    "title": entry, "message": "an encyclopedia entry already exists with the provided title."
                    })       
        
            body = form.cleaned_data["body"]
            util.save_entry(title, body)

            html = util.convert(title)
            return render(request, "encyclopedia/entry.html", {
                "title": title, "body": html
                })

# get an existing page and use it to present a form for editing
def edit(request, entry):
    #editForm = NewPageForm(initial={util.convert(request.get)})
    '''
        return render(request, "encyclopedia/edit.html", {
            "form": NewPageForm()
        })
    '''

    if request.method == "GET":
        title = entry
        content = util.get_entry(title)
        form = NewPageForm({"title": title, "body": content})
        return render(request, "encyclopedia/edit.html", {
            "form": form, "title": title
            })

    form = NewPageForm(request.POST)

    if form.is_valid():
        title = form.cleaned_data.get("title")
        body = form.cleaned_data["body"]
        util.save_entry(title, body)
        html = util.convert(title)
        return render(request, "encyclopedia/entry.html", {
            "title": title, "body": html
            })

# pick a random entry and return it
def random(request):
    entries = util.list_entries()
    num_entries = len(entries)
    random_entry = entries[randint(0, num_entries - 1)]
    html = util.convert(random_entry)
    return render(request, "encyclopedia/entry.html", {
        "title": random_entry, "body": html
        })

# find an entry from url
def titlepage(request, title):
    if util.convert(title):       
        html = util.convert(title)
        return render(request, "encyclopedia/entry.html", {
            "title": title, "body": html
        })
  
    else:
        return render(request, "encyclopedia/error.html", {
        "title": title, "message": "Page Not Found."
        })            

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

{{title}}

{% endblock %}

{% block body %}

<h1>{{title}}</h1>

{{body|safe}}

<a href="{% url 'wiki:edit' title %}">Edit This Page</a>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>




{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'encyclopedia/styles.css' %}">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia"> 
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>